// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9C3vVgb6AaYU80ad0auLeRIBgAX3wBuU',
    appId: '1:164409126088:web:6f50d09a914a55e30289fd',
    messagingSenderId: '164409126088',
    projectId: 'heloconvite-c3684',
    authDomain: 'heloconvite-c3684.firebaseapp.com',
    storageBucket: 'heloconvite-c3684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClYd9xfEHI_7upIIl5MYXkXcZ5Y0AN5kc',
    appId: '1:164409126088:android:f16d315fdec301860289fd',
    messagingSenderId: '164409126088',
    projectId: 'heloconvite-c3684',
    storageBucket: 'heloconvite-c3684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfnuvirsd_RWczgS2DBMscTv8gTOUEly4',
    appId: '1:164409126088:ios:258101455c5c28bb0289fd',
    messagingSenderId: '164409126088',
    projectId: 'heloconvite-c3684',
    storageBucket: 'heloconvite-c3684.appspot.com',
    iosBundleId: 'com.example.heloConvite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfnuvirsd_RWczgS2DBMscTv8gTOUEly4',
    appId: '1:164409126088:ios:816a360606ce45860289fd',
    messagingSenderId: '164409126088',
    projectId: 'heloconvite-c3684',
    storageBucket: 'heloconvite-c3684.appspot.com',
    iosBundleId: 'com.example.heloConvite.RunnerTests',
  );
}
